syntax = "proto3";

package serfapi;

option go_package = "pb/";

service SerfService {
  // Join cluster
  // Example: grpcurl -d '{"peers":["127.0.0.1:7946"]}' 127.0.0.1:7373 serfapi.SerfService/Join
  rpc Join(JoinRequest) returns (JoinResponse);

  // Leave cluster
  // Example: grpcurl -d '{}' 127.0.0.1:7373 serfapi.SerfService/Leave
  rpc Leave(LeaveRequest) returns (LeaveResponse);

  // Set tags
  // Example: grpcurl -d '{"tags":{"role":"buyer"}}' 127.0.0.1:7373 serfapi.SerfService/SetTags
  rpc SetTags(SetTagsRequest) returns (SetTagsResponse);

  // List members
  // Example: grpcurl 127.0.0.1:7373 serfapi.SerfService/Members
  rpc Members(MembersRequest) returns (MembersResponse);

  // Send query
  // Example: grpcurl -d '{"name":"ping","payload":"hello","timeout_ms":2000}' 127.0.0.1:7373 serfapi.SerfService/Query
  rpc Query(QueryRequest) returns (QueryResponse);

  // Broadcast user event
  // Example: grpcurl -d '{"name":"topic","payload":"hi","coalesce":false}' 127.0.0.1:7373 serfapi.SerfService/Broadcast
  rpc Broadcast(BroadcastRequest) returns (BroadcastResponse);
}

message JoinRequest {
  repeated string peers = 1;
}
message JoinResponse {
  int32 joined = 1;
}

message LeaveRequest {}
message LeaveResponse {
  string result = 1;
}

message SetTagsRequest {
  map<string, string> tags = 1;
}
message SetTagsResponse {
  bool ok = 1;
  map<string, string> tags = 2;
}

message MembersRequest {}
message Member {
  string name = 1;
  string addr = 2;
  int32 port = 3;
  int32 status = 4;
  map<string, string> tags = 5;
}
message MembersResponse {
  repeated Member members = 1;
}

message QueryRequest {
  string name = 1;
  string payload = 2;
  int32 timeout_ms = 3;
}
message QueryResponse {
  repeated QueryResult results = 1;
}
message QueryResult {
  string from = 1;
  string payload = 2;
}

message BroadcastRequest {
  string name = 1;
  string payload = 2;
  bool coalesce = 3;
}
message BroadcastResponse {
  string result = 1;
}
