// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.32.0
// source: serf.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SerfService_Join_FullMethodName      = "/serfapi.SerfService/Join"
	SerfService_Leave_FullMethodName     = "/serfapi.SerfService/Leave"
	SerfService_SetTags_FullMethodName   = "/serfapi.SerfService/SetTags"
	SerfService_Members_FullMethodName   = "/serfapi.SerfService/Members"
	SerfService_Query_FullMethodName     = "/serfapi.SerfService/Query"
	SerfService_Broadcast_FullMethodName = "/serfapi.SerfService/Broadcast"
)

// SerfServiceClient is the client API for SerfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SerfServiceClient interface {
	// Join cluster
	// Example: grpcurl -d '{"peers":["127.0.0.1:7946"]}' 127.0.0.1:7373 serfapi.SerfService/Join
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Leave cluster
	// Example: grpcurl -d '{}' 127.0.0.1:7373 serfapi.SerfService/Leave
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
	// Set tags
	// Example: grpcurl -d '{"tags":{"role":"buyer"}}' 127.0.0.1:7373 serfapi.SerfService/SetTags
	SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*SetTagsResponse, error)
	// List members
	// Example: grpcurl 127.0.0.1:7373 serfapi.SerfService/Members
	Members(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*MembersResponse, error)
	// Send query
	// Example: grpcurl -d '{"name":"ping","payload":"hello","timeout_ms":2000}' 127.0.0.1:7373 serfapi.SerfService/Query
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Broadcast user event
	// Example: grpcurl -d '{"name":"topic","payload":"hi","coalesce":false}' 127.0.0.1:7373 serfapi.SerfService/Broadcast
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
}

type serfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSerfServiceClient(cc grpc.ClientConnInterface) SerfServiceClient {
	return &serfServiceClient{cc}
}

func (c *serfServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, SerfService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serfServiceClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, SerfService_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serfServiceClient) SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*SetTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTagsResponse)
	err := c.cc.Invoke(ctx, SerfService_SetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serfServiceClient) Members(ctx context.Context, in *MembersRequest, opts ...grpc.CallOption) (*MembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembersResponse)
	err := c.cc.Invoke(ctx, SerfService_Members_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serfServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SerfService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serfServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, SerfService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerfServiceServer is the server API for SerfService service.
// All implementations must embed UnimplementedSerfServiceServer
// for forward compatibility
type SerfServiceServer interface {
	// Join cluster
	// Example: grpcurl -d '{"peers":["127.0.0.1:7946"]}' 127.0.0.1:7373 serfapi.SerfService/Join
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Leave cluster
	// Example: grpcurl -d '{}' 127.0.0.1:7373 serfapi.SerfService/Leave
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
	// Set tags
	// Example: grpcurl -d '{"tags":{"role":"buyer"}}' 127.0.0.1:7373 serfapi.SerfService/SetTags
	SetTags(context.Context, *SetTagsRequest) (*SetTagsResponse, error)
	// List members
	// Example: grpcurl 127.0.0.1:7373 serfapi.SerfService/Members
	Members(context.Context, *MembersRequest) (*MembersResponse, error)
	// Send query
	// Example: grpcurl -d '{"name":"ping","payload":"hello","timeout_ms":2000}' 127.0.0.1:7373 serfapi.SerfService/Query
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Broadcast user event
	// Example: grpcurl -d '{"name":"topic","payload":"hi","coalesce":false}' 127.0.0.1:7373 serfapi.SerfService/Broadcast
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	mustEmbedUnimplementedSerfServiceServer()
}

// UnimplementedSerfServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSerfServiceServer struct {
}

func (UnimplementedSerfServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedSerfServiceServer) Leave(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedSerfServiceServer) SetTags(context.Context, *SetTagsRequest) (*SetTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTags not implemented")
}
func (UnimplementedSerfServiceServer) Members(context.Context, *MembersRequest) (*MembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Members not implemented")
}
func (UnimplementedSerfServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSerfServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedSerfServiceServer) mustEmbedUnimplementedSerfServiceServer() {}

// UnsafeSerfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SerfServiceServer will
// result in compilation errors.
type UnsafeSerfServiceServer interface {
	mustEmbedUnimplementedSerfServiceServer()
}

func RegisterSerfServiceServer(s grpc.ServiceRegistrar, srv SerfServiceServer) {
	s.RegisterService(&SerfService_ServiceDesc, srv)
}

func _SerfService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerfService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerfService_SetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).SetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_SetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).SetTags(ctx, req.(*SetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerfService_Members_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).Members(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_Members_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).Members(ctx, req.(*MembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerfService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerfService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SerfService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SerfService_ServiceDesc is the grpc.ServiceDesc for SerfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SerfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serfapi.SerfService",
	HandlerType: (*SerfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _SerfService_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _SerfService_Leave_Handler,
		},
		{
			MethodName: "SetTags",
			Handler:    _SerfService_SetTags_Handler,
		},
		{
			MethodName: "Members",
			Handler:    _SerfService_Members_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _SerfService_Query_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _SerfService_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serf.proto",
}
