// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/serf_p2p.proto

package serf_ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamMemberEventsResponse_EventType int32

const (
	StreamMemberEventsResponse_JOIN   StreamMemberEventsResponse_EventType = 0
	StreamMemberEventsResponse_LEAVE  StreamMemberEventsResponse_EventType = 1
	StreamMemberEventsResponse_FAIL   StreamMemberEventsResponse_EventType = 2
	StreamMemberEventsResponse_UPDATE StreamMemberEventsResponse_EventType = 3
)

// Enum value maps for StreamMemberEventsResponse_EventType.
var (
	StreamMemberEventsResponse_EventType_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
		2: "FAIL",
		3: "UPDATE",
	}
	StreamMemberEventsResponse_EventType_value = map[string]int32{
		"JOIN":   0,
		"LEAVE":  1,
		"FAIL":   2,
		"UPDATE": 3,
	}
)

func (x StreamMemberEventsResponse_EventType) Enum() *StreamMemberEventsResponse_EventType {
	p := new(StreamMemberEventsResponse_EventType)
	*p = x
	return p
}

func (x StreamMemberEventsResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMemberEventsResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_serf_p2p_proto_enumTypes[0].Descriptor()
}

func (StreamMemberEventsResponse_EventType) Type() protoreflect.EnumType {
	return &file_proto_serf_p2p_proto_enumTypes[0]
}

func (x StreamMemberEventsResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMemberEventsResponse_EventType.Descriptor instead.
func (StreamMemberEventsResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{4, 0}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_serf_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serf_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Member) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Member) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_proto_serf_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serf_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{1}
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_proto_serf_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serf_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *GetMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type StreamMemberEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMemberEventsRequest) Reset() {
	*x = StreamMemberEventsRequest{}
	mi := &file_proto_serf_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMemberEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMemberEventsRequest) ProtoMessage() {}

func (x *StreamMemberEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serf_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMemberEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamMemberEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{3}
}

type StreamMemberEventsResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	EventType     StreamMemberEventsResponse_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=serf_p2p.StreamMemberEventsResponse_EventType" json:"event_type,omitempty"`
	Member        *Member                              `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMemberEventsResponse) Reset() {
	*x = StreamMemberEventsResponse{}
	mi := &file_proto_serf_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMemberEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMemberEventsResponse) ProtoMessage() {}

func (x *StreamMemberEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serf_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMemberEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamMemberEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_serf_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *StreamMemberEventsResponse) GetEventType() StreamMemberEventsResponse_EventType {
	if x != nil {
		return x.EventType
	}
	return StreamMemberEventsResponse_JOIN
}

func (x *StreamMemberEventsResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_proto_serf_p2p_proto protoreflect.FileDescriptor

const file_proto_serf_p2p_proto_rawDesc = "" +
	"\n" +
	"\x14proto/serf_p2p.proto\x12\bserf_p2p\"\xc7\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12.\n" +
	"\x04tags\x18\x05 \x03(\v2\x1a.serf_p2p.Member.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11GetMembersRequest\"@\n" +
	"\x12GetMembersResponse\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.serf_p2p.MemberR\amembers\"\x1b\n" +
	"\x19StreamMemberEventsRequest\"\xcd\x01\n" +
	"\x1aStreamMemberEventsResponse\x12M\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2..serf_p2p.StreamMemberEventsResponse.EventTypeR\teventType\x12(\n" +
	"\x06member\x18\x02 \x01(\v2\x10.serf_p2p.MemberR\x06member\"6\n" +
	"\tEventType\x12\b\n" +
	"\x04JOIN\x10\x00\x12\t\n" +
	"\x05LEAVE\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x032\xc2\x01\n" +
	"\x14SerfDiscoveryService\x12G\n" +
	"\n" +
	"GetMembers\x12\x1b.serf_p2p.GetMembersRequest\x1a\x1c.serf_p2p.GetMembersResponse\x12a\n" +
	"\x12StreamMemberEvents\x12#.serf_p2p.StreamMemberEventsRequest\x1a$.serf_p2p.StreamMemberEventsResponse0\x01B)Z'github.com/zebaMH/cometbft/p2p/serf_ipcb\x06proto3"

var (
	file_proto_serf_p2p_proto_rawDescOnce sync.Once
	file_proto_serf_p2p_proto_rawDescData []byte
)

func file_proto_serf_p2p_proto_rawDescGZIP() []byte {
	file_proto_serf_p2p_proto_rawDescOnce.Do(func() {
		file_proto_serf_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_serf_p2p_proto_rawDesc), len(file_proto_serf_p2p_proto_rawDesc)))
	})
	return file_proto_serf_p2p_proto_rawDescData
}

var file_proto_serf_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_serf_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_serf_p2p_proto_goTypes = []any{
	(StreamMemberEventsResponse_EventType)(0), // 0: serf_p2p.StreamMemberEventsResponse.EventType
	(*Member)(nil),                     // 1: serf_p2p.Member
	(*GetMembersRequest)(nil),          // 2: serf_p2p.GetMembersRequest
	(*GetMembersResponse)(nil),         // 3: serf_p2p.GetMembersResponse
	(*StreamMemberEventsRequest)(nil),  // 4: serf_p2p.StreamMemberEventsRequest
	(*StreamMemberEventsResponse)(nil), // 5: serf_p2p.StreamMemberEventsResponse
	nil,                                // 6: serf_p2p.Member.TagsEntry
}
var file_proto_serf_p2p_proto_depIdxs = []int32{
	6, // 0: serf_p2p.Member.tags:type_name -> serf_p2p.Member.TagsEntry
	1, // 1: serf_p2p.GetMembersResponse.members:type_name -> serf_p2p.Member
	0, // 2: serf_p2p.StreamMemberEventsResponse.event_type:type_name -> serf_p2p.StreamMemberEventsResponse.EventType
	1, // 3: serf_p2p.StreamMemberEventsResponse.member:type_name -> serf_p2p.Member
	2, // 4: serf_p2p.SerfDiscoveryService.GetMembers:input_type -> serf_p2p.GetMembersRequest
	4, // 5: serf_p2p.SerfDiscoveryService.StreamMemberEvents:input_type -> serf_p2p.StreamMemberEventsRequest
	3, // 6: serf_p2p.SerfDiscoveryService.GetMembers:output_type -> serf_p2p.GetMembersResponse
	5, // 7: serf_p2p.SerfDiscoveryService.StreamMemberEvents:output_type -> serf_p2p.StreamMemberEventsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_serf_p2p_proto_init() }
func file_proto_serf_p2p_proto_init() {
	if File_proto_serf_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_serf_p2p_proto_rawDesc), len(file_proto_serf_p2p_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_serf_p2p_proto_goTypes,
		DependencyIndexes: file_proto_serf_p2p_proto_depIdxs,
		EnumInfos:         file_proto_serf_p2p_proto_enumTypes,
		MessageInfos:      file_proto_serf_p2p_proto_msgTypes,
	}.Build()
	File_proto_serf_p2p_proto = out.File
	file_proto_serf_p2p_proto_goTypes = nil
	file_proto_serf_p2p_proto_depIdxs = nil
}
